sources:
    - name: siem logs
      type: directory
      location: /var/log/siem
      format: json
      tags:
        - siem
        - logs
    - name: syslog
      type: service
      location: ' '
      format: json
      tags:
        - syslog
        - logs
    - name: threat intel
      type: module
      location: /path/or/uri/to/module/output
      format: json
      tags:
        - intel
        - module
    - name: thevalve
      type: module
      location: ' '
      format: raw
      tags:
        - credentials
        - module
network:
    read_timeout: 10
    write_timeout: 10
users_database:
    path: users.db
